import 'package:assignment1_instagram_ui/Models/post_class.dart';

List<Post> tagPostList = [
  Post(
    profileImg: 'assets/profile_image/justin_profile.jpeg',
    name: 'justinbieber',
    postImage: 'assets/post_image/justin.jpeg',
    like: 2189526,
    caption: 'This is everything',
    viewComment: '10.560',
    timePost: '1 week ago',
    storyImg: 'assets/story_detail/justin_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/charlieputh_profile.jpeg',
    name: 'charlieputh',
    postImage: 'assets/post_image/charlieputh.jpeg',
    like: 641605,
    caption: 'I look like the girl from The Ring lol',
    viewComment: '4.315',
    timePost: '1 day ago',
    storyImg: 'assets/story_detail/charlieputh_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/nasa_profile.jpeg',
    name: 'nasa',
    postImage: 'assets/post_image/nasa.jpeg',
    like: 719511,
    caption: 'The Olympic games light up the right',
    viewComment: '2.193',
    timePost: '23h ago',
    storyImg: 'assets/story_detail/nasa_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/rose_profile.jpeg',
    name: 'rose_are_rosie',
    postImage: 'assets/post_image/rose.jpeg',
    like: 6864332,
    caption: '❤️😇👀',
    viewComment: '87.530',
    timePost: 'july 23',
    storyImg: 'assets/story_detail/rosee_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/jennie_profile.jpeg',
    name: 'jennie',
    postImage: 'assets/post_image/jennie.jpeg',
    like: 7107424,
    caption: 'Daydreamin about this day',
    viewComment: '97.471',
    timePost: '5 days ago',
    storyImg: 'assets/story_detail/jennie_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/avarose_profile.jpeg',
    name: 'ava.rxsee',
    postImage: 'assets/post_image/avarose.jpeg',
    like: 216251,
    caption: 'i\'m wishin\' we\'d never met😇',
    viewComment: '87.530',
    timePost: '2 days ago',
    storyImg: 'assets/story_detail/avarose_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/jisoo_profile.jpeg',
    name: 'soyaa__',
    postImage: 'assets/post_image/jisoo.jpeg',
    like: 2907126,
    caption: '#BLACKPINKTHEMOVIE #20210804',
    viewComment: '26.812',
    timePost: '5h ago',
    storyImg: 'assets/story_detail/jisoo_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/lisa_profile.jpeg',
    name: 'lalalisa_m',
    postImage: 'assets/post_image/lisa.jpeg',
    like: 7090089,
    caption: '@Bulgari',
    viewComment: '106.038',
    timePost: 'july 12',
    storyImg: 'assets/story_detail/lisa_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/tesla_profile.jpeg',
    name: 'teslamotors',
    postImage: 'assets/post_image/tesla.jpeg',
    like: 782633,
    caption: 'Model 3 deliveries in Europe',
    viewComment: '3.226',
    timePost: 'April 2',
    storyImg: 'assets/story_detail/tesla_detail.jpeg',
  ),
  Post(
    profileImg: 'assets/profile_image/instnict_profile.jpeg',
    name: 'instnict_institute',
    postImage: 'assets/post_image/instnict.jpeg',
    like: 260,
    caption: 'Workshop: "Successful Facebook Marketing"',
    viewComment: '90',
    timePost: '1 week ago',
    storyImg: 'assets/story_detail/instnict_detail.jpeg',
  ),
];